import { serviceBlueprintSchema } from "./schemas";
import { seedResident } from "./seed";
import type { FieldDefinition, ServiceBlueprint, ServiceId } from "./types";

const parkingFields: FieldDefinition[] = [
  {
    id: "vehicleId",
    serviceId: "parking_permit_renewal",
    label: "Vehicle selected for permit renewal",
    plainLabel: "Which car are you renewing the permit for?",
    description: "Choose the registered vehicle that will use the renewed resident parking permit.",
    plainDescription: "Pick the car for this permit.",
    kind: "radio",
    required: true,
    options: seedResident.vehicles.map((vehicle) => ({ label: vehicle.label, value: vehicle.id })),
    source: "portal_state",
    defaultValuePath: "resident.vehicles[0].id",
    validation: {},
  },
  {
    id: "permitDurationMonths",
    serviceId: "parking_permit_renewal",
    label: "Requested permit validity period",
    plainLabel: "How long should the new permit last?",
    description: "Select the requested duration for the resident parking permit.",
    plainDescription: "Choose six months or one year.",
    kind: "radio",
    required: true,
    options: [
      { label: "6 months — $35", value: 6 },
      { label: "12 months — $60", value: 12 },
    ],
    source: "user_input",
    validation: {},
  },
  {
    id: "contactEmail",
    serviceId: "parking_permit_renewal",
    label: "Contact email address for renewal notices",
    plainLabel: "What email should we use?",
    description: "Review or change the email address used for parking permit updates.",
    plainDescription: "We will send permit updates to this email.",
    kind: "email",
    required: true,
    source: "portal_state",
    defaultValuePath: "resident.email",
    validation: { maxLength: 254 },
  },
  {
    id: "communicationPreference",
    serviceId: "parking_permit_renewal",
    label: "Preferred renewal communication method",
    plainLabel: "How should we contact you?",
    description: "Choose how Northstar City Services should send permit updates.",
    plainDescription: "Choose email or text messages.",
    kind: "radio",
    required: false,
    options: [
      { label: "Email", value: "email" },
      { label: "SMS", value: "sms" },
    ],
    source: "user_input",
    validation: {},
  },
  {
    id: "currentPermitSummary",
    serviceId: "parking_permit_renewal",
    label: "Current resident parking permit record",
    plainLabel: "Your current parking permit",
    description: "Review the current permit expiry date and assigned resident zone before renewal.",
    plainDescription: "Check your current permit details.",
    kind: "readonly_summary",
    required: true,
    source: "portal_state",
    defaultValuePath: "resident.activeParkingPermit",
    validation: {},
  },
];

const addressFields: FieldDefinition[] = [
  {
    id: "currentAddressSummary",
    serviceId: "address_change",
    label: "Current residential address on file",
    plainLabel: "Your current address",
    description: "Review the address currently stored in the Northstar City resident record.",
    plainDescription: "Check the address we have now.",
    kind: "readonly_summary",
    required: true,
    source: "portal_state",
    defaultValuePath: "resident.address",
    validation: {},
  },
  {
    id: "newStreet",
    serviceId: "address_change",
    label: "New street address and unit information",
    plainLabel: "What is your new street address?",
    description: "Enter the house number, street name, and apartment or unit if applicable.",
    plainDescription: "Enter your new street and unit number.",
    kind: "text",
    required: true,
    source: "user_input",
    validation: { minLength: 3, maxLength: 120 },
  },
  {
    id: "newCity",
    serviceId: "address_change",
    label: "Municipality or city for the new residence",
    plainLabel: "What city is your new home in?",
    description: "Enter the city or municipality for the new home address.",
    plainDescription: "Enter your new city.",
    kind: "text",
    required: true,
    source: "user_input",
    validation: { minLength: 2, maxLength: 80 },
  },
  {
    id: "newPostalCode",
    serviceId: "address_change",
    label: "Postal code associated with the new residence",
    plainLabel: "What is the new postal code?",
    description: "Enter the postal code for the new address.",
    plainDescription: "Enter your new postal code.",
    kind: "text",
    required: true,
    source: "user_input",
    validation: { minLength: 3, maxLength: 16 },
  },
  {
    id: "effectiveDate",
    serviceId: "address_change",
    label: "Date the residential address change takes effect",
    plainLabel: "When did you move?",
    description: "Choose the date from which the new address should apply to city records.",
    plainDescription: "Choose the date your new address starts.",
    kind: "date",
    required: true,
    source: "user_input",
    validation: {},
  },
  {
    id: "updateVoterRecord",
    serviceId: "address_change",
    label: "Request an address update for the fictional voter record",
    plainLabel: "Also update your voter record?",
    description:
      "Choose whether this fictional demonstration should include a voter-record update request.",
    plainDescription: "Choose yes if you also want this record updated.",
    kind: "boolean",
    required: false,
    source: "user_input",
    validation: {},
  },
];

export const serviceBlueprints: Record<ServiceId, ServiceBlueprint> = {
  parking_permit_renewal: {
    id: "parking_permit_renewal",
    title: "Parking Permit Renewal",
    shortDescription: "Renew a fictional Northstar City resident parking permit.",
    fields: parkingFields,
    baselineJourney: [
      { id: "open-permits", label: "Open the permits section", interactionCost: 1 },
      { id: "find-renewal", label: "Find permit renewal", interactionCost: 1 },
      { id: "start-renewal", label: "Start the renewal flow", interactionCost: 1 },
      { id: "review-permit", label: "Review the current permit", interactionCost: 1 },
      { id: "choose-vehicle", label: "Choose the vehicle", interactionCost: 1 },
      { id: "choose-duration", label: "Choose the permit duration", interactionCost: 1 },
      { id: "review-fee", label: "Review the fee", interactionCost: 1 },
      { id: "confirm-email", label: "Confirm contact email", interactionCost: 1 },
      { id: "choose-contact", label: "Choose communication preference", interactionCost: 1 },
      { id: "review-terms", label: "Review the declaration", interactionCost: 1 },
      { id: "save-draft", label: "Save the draft", interactionCost: 1 },
      { id: "open-review", label: "Open the review", interactionCost: 1 },
      { id: "confirm-submission", label: "Confirm submission", interactionCost: 1 },
    ],
    allowedOperationIds: [
      "permit.load_current",
      "permit.set_vehicle",
      "permit.set_duration",
      "permit.set_contact",
      "permit.calculate_fee",
      "permit.save_draft",
      "permit.stage_review",
    ],
    finalHumanOperationId: "permit.submit",
  },
  address_change: {
    id: "address_change",
    title: "Address Change",
    shortDescription: "Update a fictional Northstar City residential address.",
    fields: addressFields,
    baselineJourney: [
      { id: "open-records", label: "Open resident records", interactionCost: 1 },
      { id: "find-address", label: "Find address change", interactionCost: 1 },
      { id: "start-change", label: "Start the change flow", interactionCost: 1 },
      { id: "review-current", label: "Review the current address", interactionCost: 1 },
      { id: "enter-street", label: "Enter the new street", interactionCost: 1 },
      { id: "enter-city", label: "Enter the new city", interactionCost: 1 },
      { id: "enter-postal", label: "Enter the new postal code", interactionCost: 1 },
      { id: "choose-date", label: "Choose the effective date", interactionCost: 1 },
      { id: "voter-preference", label: "Choose voter-record preference", interactionCost: 1 },
      { id: "save-draft", label: "Save the draft", interactionCost: 1 },
      { id: "review", label: "Review the update", interactionCost: 1 },
      { id: "confirm", label: "Confirm submission", interactionCost: 1 },
    ],
    allowedOperationIds: [
      "address.load_current",
      "address.set_new",
      "address.set_effective_date",
      "address.set_voter_preference",
      "address.validate",
      "address.save_draft",
      "address.stage_review",
    ],
    finalHumanOperationId: "address.submit",
  },
};

for (const blueprint of Object.values(serviceBlueprints)) {
  serviceBlueprintSchema.parse(blueprint);
}

export const getServiceBlueprint = (serviceId: ServiceId): ServiceBlueprint =>
  serviceBlueprints[serviceId];
